# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: codeby-2

---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: codeby
spec:
  containers:
  - name: nginx-2
    image: nginx
