Vagrant.configure("2") do |config|  # Настройки виртуальной машины server
  config.vm.define "server" do |server| 
    server.vm.box = "ubuntu/focal64"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.hostname = "server"
        # Подключение внешнего скрипта для настройки server
    server.vm.provision "shell", path: "server_provision.sh" 
  end
  # Настройки виртуальной машины client
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/focal64"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.hostname = "client"
        # Подключение внешнего скрипта для настройки client
    client.vm.provision "shell", path: "client_provision.sh"
  end
end
