- name: Add MySQL YUM repository (CentOS/RHEL) 
  yum:
    name: "{{ mysql_yum_repo }}"   
    state: present
  when: ansible_os_family == 'RedHat'
  become: yes

- name: Install MySQL server package 
  package:
    name: "{{ mysql_server_package }}"
    state: present
  become: yes

- name: Start MySQL service
  service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes
  become: yes
