 Vagrant.configure("2") do |config|  config.vm.provider "virtualbox" do |vb|
    # Настройка памяти и CPU    vb.memory = "1024"
    vb.cpus = 2  end
  #Определение ВМ server  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/bionic64"    server.vm.network "private_network", ip: "192.168.56.4"
    server.vm.provision "shell", path: "provision-server.sh"  end
  # Определение ВМ client
  config.vm.define "client" do |client|    client.vm.box = "ubuntu/bionic64"
    client.vm.network "private_network", ip: "192.168.56.5"    # Провиженинг клиента
    client.vm.provision "shell", path: "provision-client.sh"  end
end