pipeline {
    agent { label 'maven' }
    stages {
        stage('Build') {
            steps {
                sh '''
                    cd lesson26
                    mvn -B -DskipTests clean package
                '''
            }
        }
        stage('Test') {
            steps {
                sh ''' 
                   
                    mvn test
                '''
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
   //     stage('Deliver') {
     //       steps {
       //         sh './jenkins/scripts/deliver.sh'
         //   }
        //}
    }
}
