services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    volumes:
      - mysql_data:/var/lib/mysql # volume for db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  app:
    image: wordpress:latest
    container_name: wordpress_app
    volumes:
      - wordpress_data:/var/www/html #volume for wp data
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - frontend
      - backend

  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # bind mount
    ports:
      - "80:80" # host --> nginx_proxy
    depends_on:
      - app
    networks:
      - frontend

volumes:
  mysql_data: {}
  wordpress_data: {}

networks:
  frontend:
  backend:
